version: '3'

services:
  finances-agent:
    build: .
    container_name: finances-agent
    ports:
      - "8501:8501"
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./table_mapping.json:/app/table_mapping.json:ro
      - ./src:/app/src:ro
    env_file:
      - .env
    restart: unless-stopped